includes:
- common/defaults/configs/tasks/vqa/vqa_introspect.yml
model_attributes:
  pythia_introspect: &pythia
    model_data_dir: ../data/
    metrics:
    - type: consistency
    - type: reasoning_accuracy
    - type: sub_accuracy
    - type: other_accuracy
    - type: total_accuracy
    - type: ranking_accuracy
    losses:
    - type: multi
      params:
      - type: logit_bce_reas
        weight: 1
        params: {}
      - type: distance_importance_loss
        weight: 0.0001
        params: {}
    classifier:
      type: logit
      params:
        img_hidden_dim: 5000
        text_hidden_dim: 300
    image_feature_embeddings:
    - modal_combine:
        type: non_linear_element_multiply
        params:
          dropout: 0
          hidden_dim: 5000
      normalization: softmax
      transform:
        type: linear
        params:
          out_dim: 1
    image_feature_dim: 2048
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: detectron/fc6/fc7_b.pkl
        weights_file: detectron/fc6/fc7_w.pkl
    - type: default
      params: {}
    image_text_modal_combine:
      type: non_linear_element_multiply
      params:
        dropout: 0
        hidden_dim: 5000
    text_embeddings:
    - type: attention
      params:
        hidden_dim: 1024
        num_layers: 1
        conv1_out: 512
        conv2_out: 2
        dropout: 0
        embedding_dim: 300
        kernel_size: 1
        padding: 0
  pythia_image_only: *pythia
  pythia_question_only: *pythia
optimizer_attributes:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.01
    weight_decay: 0
training_parameters:
  clip_norm_mode: all
  clip_gradients: true
  lr_ratio: 0.1
  lr_scheduler: true
  lr_steps:
  - 15000
  - 18000
  - 20000
  - 21000
  max_grad_l2_norm: 0.25
  max_iterations: 22000
  use_warmup: true
  warmup_factor: 0.2
  warmup_iterations: 1000
  patience: 4000
  batch_size: 8
  num_workers: 7
  task_size_proportional_sampling: true
  monitored_metric: ranking_accuracy
  metric_minimize: false
